version: '3'
services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - 3307:3306
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - node-network
  app:
    depends_on:
      - mysql_db
    build: .
    container_name: cons-node
    env_file: .env
    environment:
      - DB_HOST=mysql_db
      - DB_DIALECT=$DB_DIALECT
      - DB_NAME=$DB_NAME
      - DB_PORT=3307
      - DB_ROOT=$DB_USER
      - DB_PASS=$DB_PASSWORD
    ports:
     - "3200:80"
    networks:
      - node-network
volumes:
  mysql_db:
    driver: local
networks:
  node-network: