version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: maria-docker
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db_booking
    ports:
      - 3306:3306
    volumes:
      - maria-data:/var/lib/mysql
    networks:
      - node-network
  app:
    depends_on:
      - mariadb
    build: .
    container_name: cons-node
    env_file: .env
    environment:
      - DB_HOST=mysql_db
      - DB_DIALECT=mysql
      - DB_NAME=db_booking
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=1234
    ports:
     - "3200:8080"
    networks:
      - node-network
volumes:
  mysql_db:
    driver: local
networks:
  node-network: